### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by jfoclpf**
Nice list, thanks.
With this newly proposed file I can have this repo as dependency on my npm project and then get easily the latest version of your dist folder. See more info here: https://docs.npmjs.com/cli/v7/commands/npm-install

### CODE REVIEW

**Comment by petarov** [comment]
Hi, 
This is interesting. I haven't thought about npm publishing. I suppose you're using the `diet/google-app-ids.json` file in your project, right?

**Comment by jfoclpf** [comment]
Hi @petarov , yes, I'm using that json, but now I need to copy-paste it to my project. With `package.json` I don't need to copy-paste it, I simply download the latest version of it when I update my project with `npm update` and then I have it locally. And you don't need to publish to npm, you just need that file, as then I can do `npm install https://github.com/petarov/google-android-app-ids`

or any of these options

```
npm install git+ssh://git@github.com:npm/cli.git#v1.0.27
npm install git+ssh://git@github.com:npm/cli#pull/273
npm install git+ssh://git@github.com:npm/cli#semver:^5.0
npm install git+https://isaacs@github.com/npm/cli.git
npm install git://github.com/npm/cli.git#v1.0.27
npm install mygithubuser/myproject
npm install github:mygithubuser/myproject
```

Check: https://docs.npmjs.com/cli/v7/commands/npm-install

**Comment by jfoclpf** [comment]
And after you update the list you just need to do `npm version patch` to advance in the version, such that others know an update of the list is available

**Comment by petarov** [comment]
Very cool! I didn't know about the `npm install git:..` thing. 
Thank you for your contrib 👍

**Comment by jfoclpf** [comment]
great, I just did 

`npm install github:petarov/google-android-app-ids`

and it worked perfectly as expected.

Perhaps you may want to add a note thereof in `readme.md`

**Comment by petarov** [comment]
Sure, it's in the latest README.

**Pull request merged**
